codecov:
  require_ci_to_pass: false

fixes:
  - "/home/circleci/project/::"        # reduce root e.g., "before/path/" => "path/"

coverage:
  status:
    project:
      default:
        target: auto

