version: 2.1

orbs:
  python: rohanpm/python@1.3.0

jobs:
  build:
    executor: python27
    steps:
      - checkout
      - python/load-cache
      - run:
          command: python setup.py install
      - python/save-cache


  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build
