version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:2.7.18
    steps:
      - checkout
      - python/load-cache
      - run:
          command: sudo python setup.py install
      - run:
          command: sudo python setup.py develop
      - python/save-cache
      - run:
          command: nosetests tests

workflows:
  main:
    jobs:
      - build-and-test
